name: cse23523
description: Event Manager App for exam
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2   # Use the latest versions
  cloud_firestore: ^5.0.2 # Use the latest versions
  intl: ^0.19.0           # Use the latest versions
  uuid: ^4.4.0            # For unique IDs
  image_picker: ^1.0.7
  firebase_storage: 12.4.10

flutter:
  uses-material-design: true
  # assets:
  #   - assets/event_placeholder.png
